# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  rgQA: 'test7'
  rgLive: 'test8'


stages:
- stage: Stage1
  variables:
    stga: 1-1
    stgb: 1-2
  jobs:
  - job: Stage1Job1
    variables:
      joba: 1-1-1
      jobb: 1-1-2
    pool:
      vmImage: windows-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure (VSE with MSDN)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          echo setting the variable...
          Write-Host "##vso[task.setvariable variable=job1var;isOutput=true;]$(joba)"
          echo variable set
      displayName: 'Stage1Job1Step1'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure (VSE with MSDN)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          echo test001
          Write-Host "has variable worked S job1var : $(job1var)"
          #echo has variable worked S job1var : $(job1var)
    - script: |
        echo simple cmd.exe script
      displayName: 'Stage1Job1Step2'


  - job: Stage1Job2
    dependsOn: ['Stage1Job1']
    variables:
      jobc: 1-2-1
      jobd: 1-2-2
      job1var: $[ dependencies.Stage1Job1.outputs['job1var'] ]
    pool:
      vmImage: windows-latest
    steps:
    - script: |
        echo Hello, world!
        echo test job variable
        echo other job $(joba)
        echo other job test on same line inside single quote: $(jobb)
        echo 'test stage var'
        echo $(stga)
        echo 'test root var'
        echo $(rgQA)
        echo test this job variable
        echo this job $(joba)
        echo this job test on same line inside single quote: $(jobb)
        echo **********************
        echo ** var from job 1 ****
        echo was......: $(job1var)
      displayName: 'Stage1Job2Step1'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Some other script'


- stage: StageInfrastructureQA
  jobs:
  - job: JobInfrastructureReleaseQA
    pool: 
      vmImage: 'windows-latest'
    variables:
      templateFile: './infrastructure/main.bicep'
      qaTemplateParameterFile: './infrastructure/main.parameters.qa.json'
    steps:
      - task: AzureCLI@2
        displayName: 'InfQA Task1'
        inputs:
          azureSubscription: 'Azure (VSE with MSDN)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            echo 'try and show displayName'
            echo '$(displayName)'

      - task: AzureCLI@2
        displayName: 'InfQA Task2'
        inputs:
          azureSubscription: 'Azure (VSE with MSDN)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            echo 'try and show displayName'
            echo '$(displayName)'
      - script: echo Hello, world!
      - script: |
          echo Hello, world!
          echo test job variable
          echo $(joba)
          echo 'test on same line inside single quote: $(jobb)'
          echo 'test stage var'
          echo $(stga)
          echo 'test root var'
          echo $(rgQA)
        displayName: 'Run a one-line script'
      - task: AzureCLI@2
        displayName: 'InfQA Task3'
        inputs:
          azureSubscription: 'Azure (VSE with MSDN)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            echo 'try and show displayName'
            echo '$(displayName)'          


- stage: DeployQA
  jobs:
  - job: DeployQA
